#!/bin/bash

rmmod mac802154_hwsim
rmmod mac802154
rmmod ieee802154_6lowpan
rmmod ieee802154
modprobe mac802154_hwsim

n=`echo $1'/2' | bc`

for i in `seq 0 $n`
do
	wpan-hwsim add
done

# BUILD TOPOLOGY
for i in `seq 0 $n`
do
	if [ "$i" == 0 ]
	then
		eval "wpan-hwsim edge add "$i' '`expr $i + 1`
	        eval "wpan-hwsim edge add " `expr $i + 1`' '$i	
	else
		if [ "$i" -gt `expr 5 + 1` -a `expr "$i" % 5` != 1 ]
		then
			eval "wpan-hwsim edge add "$i' '`expr $i - 6`
		        eval "wpan-hwsim edge add " `expr $i - 6`' '$i
		fi
		if [ "$i" -gt 5 -a `expr "$i" % 5` != 0 ]
		then
			eval "wpan-hwsim edge add "$i' '`expr $i - 4`
		        eval "wpan-hwsim edge add " `expr $i - 4`' '$i
		fi
		if [ `expr "$i" % 5` != 0 ]
		then
			eval "wpan-hwsim edge add "$i' '`expr $i + 1`
		        eval "wpan-hwsim edge add " `expr $i + 1`' '$i
		fi
		if [ "$i" -lt `expr $n - 4` ]
		then
			eval "wpan-hwsim edge add "$i' '`expr $i + 5`
		        eval "wpan-hwsim edge add " `expr $i + 5`' '$i
		fi
	fi
	ip netns add ns$i
	iwpan phy phy$i set netns name ns$i
	ip netns exec ns$i iwpan dev wpan$i set pan_id 0xbeef
	ip netns exec ns$i ip link add link wpan$i name lowpan$i type lowpan
	ip netns exec ns$i ip link set wpan$i up
	ip netns exec ns$i ip link set lowpan$i up 
done
